<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Priostack.Acn.ShareQuickstart</RootNamespace>
    <AssemblyName>Priostack.Acn.ShareQuickstart</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Priostack.Acn\Priostack.Acn.csproj" />
  </ItemGroup>

</Project>
